import { StyleSheet } from 'react-native';

import { Theme } from '../../theme';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      padding: 20,
      paddingBottom: 32,
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      marginBottom: 4,
    },
    subtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 16,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    dateNav: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    navButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    navButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    heroCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      padding: 20,
      alignItems: 'center',
      marginBottom: 20,
    },
    glassWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      height: 280,
      width: 200,
    },
    glass: {
      width: 160,
      height: 220,
      borderRadius: 24,
      borderWidth: 2,
      borderColor: theme.colors.textSecondary,
      backgroundColor: theme.colors.surface,
      overflow: 'hidden',
      position: 'relative',
    },
    glassFill: {
      width: '100%',
      backgroundColor: '#7EC8FF',
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      position: 'absolute',
      bottom: 0,
    },
    glassShine: {
      position: 'absolute',
      left: 14,
      top: 18,
      width: 10,
      height: 180,
      borderRadius: 6,
      backgroundColor: 'rgba(255, 255, 255, 0.6)',
    },
    progressCenter: {
      position: 'absolute',
      alignItems: 'center',
    },
    progressValue: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    progressGoal: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      marginTop: 4,
    },
    ripple: {
      position: 'absolute',
      width: 200,
      height: 200,
      borderRadius: 100,
      borderWidth: 1,
      borderColor: theme.colors.primary,
    },
    quickAddRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 20,
    },
    quickAddButton: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
    },
    quickAddCustom: {
      backgroundColor: theme.colors.primary,
    },
    quickAddReset: {
      backgroundColor: theme.colors.background,
    },
    quickAddText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textSecondary,
    },
    quickAddTextLight: {
      color: '#FFFFFF',
    },
    goalCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 18,
      padding: 16,
      gap: 10,
    },
    goalTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    goalSubtitle: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    goalInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: 12,
    },
    goalInput: {
      flex: 1,
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.textSecondary,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 16,
      color: theme.colors.textPrimary,
    },
    goalUnitLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    unitToggle: {
      flexDirection: 'row',
      gap: 10,
    },
    unitChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: theme.colors.background,
    },
    unitChipActive: {
      backgroundColor: theme.colors.primary,
    },
    unitChipText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.textSecondary,
    },
    unitChipTextActive: {
      color: '#FFFFFF',
    },
    reminderCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 18,
      padding: 16,
      marginTop: 16,
      gap: 12,
    },
    reminderHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    reminderTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    reminderSubtitle: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginTop: 4,
    },
    reminderToggle: {
      width: 44,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.textSecondary,
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    reminderToggleActive: {
      backgroundColor: theme.colors.primary,
      borderWidth: 0,
    },
    reminderKnob: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: theme.colors.textSecondary,
      alignSelf: 'flex-start',
    },
    reminderKnobActive: {
      alignSelf: 'flex-end',
      borderWidth: 0,
    },
    reminderHours: {
      flexDirection: 'row',
      gap: 12,
    },
    reminderInputGroup: {
      flex: 1,
      gap: 6,
    },
    reminderLabel: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    reminderInput: {
      borderRadius: 12,
      backgroundColor: theme.colors.background,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    reminderHint: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.35)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: theme.colors.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: 24,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: 'center',
      marginBottom: 12,
    },
    modalInput: {
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: theme.colors.textPrimary,
      marginBottom: 12,
    },
    modalButton: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
    },
    modalButtonText: {
      color: '#FFFFFF',
      fontWeight: '700',
    },
  });
